{% set version = '1.2-1' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-coin
  version: {{ version|replace("-", "_") }}

source:
  fn: coin_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/coin_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/coin/coin_{{ version }}.tar.gz
  sha256: 612103149a006cdadfc003925d4498bed2dc8831a32f064d415c4cab9dfaddd2


  # patches:
   # List any patch files here
   # - fix.patch

build:
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: parallel, xtable, e1071, vcd, TH.data (>= 1.0-7), libcoin (>= 0.9-0)
requirements:
  build:
    - r-base
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('fortran') }}  # [not win]
    - {{native}}toolchain        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make
    - r-modeltools >=0.2_9
    - r-multcomp
    - r-mvtnorm >=1.0_5
    - r-survival

  run:
    - r-base
    - {{native}}gcc-libs         # [win]
    - r-modeltools >=0.2_9
    - r-multcomp
    - r-mvtnorm >=1.0_5
    - r-survival

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('coin')"           # [not win]
    - "\"%R%\" -e \"library('coin')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: http://coin.r-forge.r-project.org
  license: GPL-2
  summary: Conditional inference procedures for the general independence problem including two-sample,
    K-sample (non-parametric ANOVA), correlation, censored, ordered and multivariate
    problems.
  license_family: GPL2

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: coin
# Version: 1.2-1
# Date: 2017-07-16
# Title: Conditional Inference Procedures in a Permutation Test Framework
# Authors@R: c(person("Torsten", "Hothorn", role = c("aut", "cre"), email = "Torsten.Hothorn@R-project.org"), person("Kurt", "Hornik", role = "aut"), person("Mark A.", "van de Wiel", role = "aut"), person("Henric", "Winell", role = "aut"), person("Achim", "Zeileis", role = "aut"))
# Description: Conditional inference procedures for the general independence problem including two-sample, K-sample (non-parametric ANOVA), correlation, censored, ordered and multivariate problems.
# Depends: R (>= 2.14.0), methods, survival
# Imports: stats, modeltools (>= 0.2-9), mvtnorm (>= 1.0-5), multcomp
# Suggests: parallel, xtable, e1071, vcd, TH.data (>= 1.0-7), libcoin (>= 0.9-0)
# LazyData: yes
# NeedsCompilation: yes
# ByteCompile: yes
# License: GPL-2
# URL: http://coin.r-forge.r-project.org
# Packaged: 2017-07-17 09:10:20 UTC; hothorn
# Author: Torsten Hothorn [aut, cre], Kurt Hornik [aut], Mark A. van de Wiel [aut], Henric Winell [aut], Achim Zeileis [aut]
# Maintainer: Torsten Hothorn <Torsten.Hothorn@R-project.org>
# Repository: CRAN
# Date/Publication: 2017-07-17 22:32:53 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
