travis:
  secure:
    BINSTAR_TOKEN: o0ru5PGjOFEZ67ZqKvLLYisr9sNQEm+OOpna2dvvWbCiODoG20Q9MHRsYW8VZbiMT/9UFx3dNaZ2fYf6ACTuh5UWcD4uHfLzWofoOWrUGtngCctanlwYrpbtOMNUKdxAmRnTAbaqSwW9QgXBWkTITJxYNfFTfA6VqICICL7z0MFfn3fPJqJDOBo72y+AGKKumwA2bB2cZwKfy+y6JwmKZlB+W5cRYh5OIVxtF1zWxFYkAlYubtDLfSWeHi8yz8lk/vba+6Ri7KLaTpD696U5mynJ+gV9UFpMx8Dc7vShXJswWmpnTCO4+FT6WpyGSbcTuAqQv2e3sN0DQzAnz98rHf3CzVLdS0g5DodZUX4OHUGdhua+gk43N4/yquBtonYe/U4fq0mMb0re+qp/OvEg+1WhkxsJ7Vp/xbaq+N9Xx4bsAs1C0O07WqXeCD+63zjPG83a/BR/psSj4umQiBKZ/Q7ICSVrj8psf7wYA2+eH75AUzkEEmU2L9mf6twK/4qqFNDBXJoaII94yW6myZ3UICH8Hag3/HcWIcZ04fsTroC0aSDifLp75bg5w+4x/Pnoc3q+Kf38SVCsfSSw9/czVneUK5+WLvbyHcvfMe4Rq/9rMnHfVzzNNSHTQdy3FyzPgVfV8H5F/V+346TFxIw8+aDQZObSPICkVyqRLBhaMcs=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
