travis:
  secure:
    BINSTAR_TOKEN: BUpMmXtDd2WR9gUomdNrSP1iSYYx6cQs2gMH2h4Rdiir7WZkIAjDvNjhjlvO3L9Ak9AqlNv85R6Gq5F6Qz7rXseTtJ+mhkN2nNb6t582qxEnCUaQmjipo6dJMR/e64IM1MtiGga6ieRBZT9mUt1XHr2h0i9bhilu2a65oDJWWceQNFj7yEvJ7uUvGqg+Ro24yRIEsUKwucn6EVFDv2V6q6Bv/nsb98HxtCIK8z444NuqRq0RQro7xhLS66QtIneD2lnNAl1r3oxYigaK1jaM6rub+lwsdNxY6PNrfSq567ZqPJ2XygZUqTDXkmFhQAoknDD1oRRKFbZIx6tzK4TAsYkrAyzKJP7H5J+6SnAS+DjHAxbx/UpdjS51AFlFM4x7/TmUy97v9fUxvGhTvsVtN5J3WexfE+J8aesYMncJ3jUVvoOlGKxIaQEosUARYei+jPONEX7s+GgTe3ZKYUHiHWs+rc+ZXgd5EjneWHclxPV1QtQQhN8QISS6gVvKPWg2G3B53sNq4POAmgTiHJ/5c3M34WlYf1wjkdWhwsRKYJRqwBPfZ9vua6cxaFaspKw5AsclyV2U8P8Ts9CJbGT+EWySTgLhMd8MO6eO12z4jUpVQsCDBD2NgyaucyOoxEzaXul9IEljHUcCyp6JHrpwtmDyTzZhNTqTvHfb9c1yRYE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
