travis:
  secure:
    BINSTAR_TOKEN: LWkmfYNGLAElVYtQCre3tM6ILVzYCogba0B0m2uAS6vovCObD4/f5mL/tUz9dhUiQMm9JaTFybkgVNQWA97XoIeNje1gn375tauYMZKzTvXBhLyx1atunP1TjpKxNmzLpR/iBpP85DZ4bK1IBfGwEsSdr4LGm82jUD9a4tnFsoVQ4rYRiIZ+M1UiGk3uvcQjEW/tjp34rYNPuOHG1inWWtmLNbq91BqKvmeO9UhXXML1rHUsKz0HMa2qWw8OY7Fow5EAY9bCiZaX31wN98ypDpJxnxVUNq9jwZbV2CG2sC+m1iJU2JbApgmCFRq8YHCbeAWDk2cLDyPaQpRZ6+cKErR06Xp0Acp4dNM9DPOVbQJhAU0aZbc8bEJLVQDwiMkik135puUHTbHQRNubvAuVpLmJ3PcbUU4/uL7kFvl/MOshsN5aJAkME1chmsDNre3EWZY3Y4Dpg8E+Kf5u5ACICeD/ulA3WJVuloxiAwBQhgagT5gMfqYHWHbGb/DDPCXL6Rny0ubX/sEUTjj2fMi9ovO29VIScDNjcMaVEqVQVCI7v6+Ee8RpbEof4WitlVX5Z4lp9fZR0Zy/xfXBV+McgcAd+iW22wdUddb7GtlMgPsecHCekPf8h5KdELqSUUt4QAN9VvSwhSeKqZtT7hcwkZnKvfdOESG1aFWjWKipZwk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
